server:
  port: 8080
  servlet:
    context-path: /weather-service

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        validator:
          apply_to_ddl: false
        format_sql: true
weather:
  simulation:
    days: 3650
  planet:
    Ferengi:
      angular-speed: 1
      clockwise: true
      sun-distance: 500
    Betasoide:
      angular-speed: 3
      clockwise: true
      sun-distance: 2000
    Vulcano:
      angular-speed: 5
      clockwise: false
      sun-distance: 1000
